"""initial schema

Revision ID: 0a5c613a3a00
Revises: 
Create Date: 2026-04-25 14:24:01.715934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a5c613a3a00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_code', sa.String(length=10), nullable=False))
        batch_op.create_index(batch_op.f('ix_team_invite_code'), ['invite_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_invite_code'))
        batch_op.drop_column('invite_code')

    # ### end Alembic commands ###
